name: Continuous integration

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use the same version of Node.js that is specified in package.json
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Run unit tests
        run: CI=true npm run test:unit

      - name: Run E2E tests
        run: npm run test:e2e
